# Generated by Django 3.2.5 on 2021-07-19 02:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('race', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birthsign', models.CharField(blank=True, max_length=10, null=True)),
                ('char_class', models.CharField(blank=True, max_length=20, null=True)),
                ('hometown', models.CharField(blank=True, max_length=30, null=True)),
                ('backstory', models.TextField(blank=True, max_length=560, null=True)),
                ('disposition', models.CharField(blank=True, max_length=30, null=True)),
                ('violence', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('passivity', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('selfishness', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('compliance', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('trust', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('empathy', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('likes', models.TextField(blank=True, max_length=280, null=True)),
                ('deslikes', models.TextField(blank=True, max_length=280, null=True)),
                ('weapons', models.TextField(blank=True, max_length=280, null=True)),
                ('spells', models.TextField(blank=True, max_length=280, null=True)),
                ('armor', models.TextField(blank=True, max_length=280, null=True)),
                ('forbidden_equip', models.TextField(blank=True, max_length=280, null=True)),
                ('forbidden_magic', models.TextField(blank=True, max_length=280, null=True)),
                ('worship', models.TextField(blank=True, max_length=280, null=True)),
                ('factions', models.TextField(blank=True, max_length=280, null=True)),
                ('forbidden_factions', models.TextField(blank=True, max_length=280, null=True)),
                ('deseases', models.TextField(blank=True, max_length=280, null=True)),
                ('handicaps', models.TextField(blank=True, max_length=280, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
